apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgrest
  namespace: zk-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgrest
  template:
    metadata:
      labels:
        app: postgrest
    spec:
      containers:
      - name: postgrest
        image: postgrest/postgrest
        ports:
        - containerPort: 3000
        env:
        - name: PGRST_DB_URI
          valueFrom:
            secretKeyRef:
              name: postgres
              key: postgres-uri
        - name: PGRST_DB_ANON_ROLE
          value: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: postgrest-service
  namespace: zk-client
spec:
  selector:
    app: postgrest
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: ClusterIP
