apiVersion: v1
kind: ConfigMap
metadata:
  name: webdis
  namespace: zk-client
data:
  webdis.json: |
   {
      "redis_host": "redis-master.zk-client.svc.cluster.local",

      "redis_port": 6379,
      "redis_auth": "RUZpgGGfsW",

      "http_host":  "0.0.0.0",
      "http_port":  7379,
      "threads":  4,

      "daemonize": false,

      "database": 0,

      "acl": [
        {
          "disabled": ["DEBUG"]
        },

        {
          "http_basic_auth":  "user:password",
          "enabled":    ["DEBUG"]
        }
      ],
      "hiredis": {
        "keep_alive_sec": 15
      },

      "verbosity": 3,
      "logfile": "/var/log/webdis.log"
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webdis
  namespace: zk-client
  labels:
    app: webdis
spec:
  replicas: 1 # You can define the number of replicas
  selector:
    matchLabels:
      app: webdis
  template:
    metadata:
      labels:
        app: webdis
    spec:
      containers:
        - name: webdis
          image: nicolas/webdis:latest
          ports:
            - containerPort: 7379
          command: ["/bin/sh", "-c", "/usr/local/bin/webdis /opt/webdis.json"]
          volumeMounts:
            - mountPath: /opt
              name: config-volume
      volumes:
        - name: config-volume
          configMap:
            name: webdis
---
apiVersion: v1
kind: Service
metadata:
  name: webdis
  namespace: zk-client
spec:
  selector:
    app: webdis
  ports:
    - protocol: TCP
      port: 7379
      targetPort: 7379
  type: ClusterIP
